version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - REACT_APP_API_URL=https://spend-time-together.ru/api
    container_name: spend-time-together-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true